# Data Cleaning
* Library
* Load Data
1. Data Understanding
2. Missimg Value 
3. Duplicates
4. Inconsistent Data

# Library

In [ ]:
import pandas as pd

# Load Data

In [ ]:
# مسیر فایل
data = r"Dataset\Mushroom\agaricus-lepiota.data"

columns = [ "class", "cap-shape", "cap-surface", "cap-color", "bruises",
            "odor", "gill-attachment", "gill-spacing", "gill-size", "gill-color",
            "stalk-shape", "stalk-root", "stalk-surface-above-ring", 
            "stalk-surface-below-ring", "stalk-color-above-ring",
            "stalk-color-below-ring", "veil-type", "veil-color", 
            "ring-number", "ring-type",
            "spore-print-color", "population", "habitat" ]

dataset = pd.read_csv(data, header=None, names=columns)

# 1. Data Understanding

In [85]:
dataset.head()

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
0,p,x,s,n,t,p,f,c,n,k,...,s,w,w,p,w,o,p,k,s,u
1,e,x,s,y,t,a,f,c,b,k,...,s,w,w,p,w,o,p,n,n,g
2,e,b,s,w,t,l,f,c,b,n,...,s,w,w,p,w,o,p,n,n,m
3,p,x,y,w,t,p,f,c,n,n,...,s,w,w,p,w,o,p,k,s,u
4,e,x,s,g,f,n,f,w,b,k,...,s,w,w,p,w,o,e,n,a,g

In [86]:
print("Shape:", dataset.shape)

Shape: (8124, 23)

In [87]:
# اطلاعات کلی
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8124 entries, 0 to 8123
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   class                     8124 non-null   object
 1   cap-shape                 8124 non-null   object
 2   cap-surface               8124 non-null   object
 3   cap-color                 8124 non-null   object
 4   bruises                   8124 non-null   object
 5   odor                      8124 non-null   object
 6   gill-attachment           8124 non-null   object
 7   gill-spacing              8124 non-null   object
 8   gill-size                 8124 non-null   object
 9   gill-color                8124 non-null   object
 10  stalk-shape               8124 non-null   object
 11  stalk-root                8124 non-null   object
 12  stalk-surface-above-ring  8124 non-null   object
 13  stalk-surface-below-ring  8124 non-null   object
 14  stalk-color-above-ring    8124 non-null   object
 15  stalk-color-below-ring    8124 non-null   object
 16  veil-type                 8124 non-null   object
 17  veil-color                8124 non-null   object
 18  ring-number               8124 non-null   object
 19  ring-type                 8124 non-null   object
 20  spore-print-color         8124 non-null   object
 21  population                8124 non-null   object
 22  habitat                   8124 non-null   object
dtypes: object(23)
memory usage: 1.4+ MB

In [95]:
dataset.describe(include='all')

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
count,8124,8124,8124,8124,8124,8124,8124,8124,8124,8124,...,8124,8124,8124,8124,8124,8124,8124,8124,8124,8124
unique,2,6,4,10,2,9,2,2,2,12,...,4,9,9,1,4,3,5,9,6,7
top,e,x,y,n,f,n,f,c,b,b,...,s,w,w,p,w,o,p,w,v,d
freq,4208,3656,3244,2284,4748,3528,7914,6812,5612,1728,...,4936,4464,4384,8124,7924,7488,3968,2388,4040,3148

In [96]:
# بررسی کلاس‌ها
(dataset["class"].value_counts())

class
e    4208
p    3916
Name: count, dtype: int64

In [ ]:
# بررسی توزیع هر ستون
for col in dataset.columns:
    print(f"\nColumn: {col}")
    print(dataset[col].value_counts())

Column: class
class
e    4208
p    3916
Name: count, dtype: int64

Column: cap-shape
cap-shape
x    3656
f    3152
k     828
b     452
s      32
c       4
Name: count, dtype: int64

Column: cap-surface
cap-surface
y    3244
s    2556
f    2320
g       4
Name: count, dtype: int64

Column: cap-color
cap-color
n    2284
g    1840
e    1500
y    1072
w    1040
b     168
p     144
c      44
u      16
r      16
Name: count, dtype: int64

Column: bruises
bruises
f    4748
t    3376
Name: count, dtype: int64

Column: odor
odor
n    3528
f    2160
s     576
y     576
a     400
l     400
p     256
c     192
m      36
Name: count, dtype: int64

Column: gill-attachment
gill-attachment
f    7914
a     210
Name: count, dtype: int64

Column: gill-spacing
gill-spacing
c    6812
w    1312
Name: count, dtype: int64

Column: gill-size
gill-size
b    5612
n    2512
Name: count, dtype: int64

Column: gill-color
gill-color
b    1728
p    1492
w    1202
n    1048
g     752
h     732
u     492
k     408
e      96
y      86
o      64
r      24
Name: count, dtype: int64

Column: stalk-shape
stalk-shape
t    4608
e    3516
Name: count, dtype: int64

Column: stalk-root
stalk-root
b    3776
?    2480
e    1120
c     556
r     192
Name: count, dtype: int64

Column: stalk-surface-above-ring
stalk-surface-above-ring
s    5176
k    2372
f     552
y      24
Name: count, dtype: int64

Column: stalk-surface-below-ring
stalk-surface-below-ring
s    4936
k    2304
f     600
y     284
Name: count, dtype: int64

Column: stalk-color-above-ring
stalk-color-above-ring
w    4464
p    1872
g     576
n     448
b     432
o     192
e      96
c      36
y       8
Name: count, dtype: int64

Column: stalk-color-below-ring
stalk-color-below-ring
w    4384
p    1872
g     576
n     512
b     432
o     192
e      96
c      36
y      24
Name: count, dtype: int64

Column: veil-type
veil-type
p    8124
Name: count, dtype: int64

Column: veil-color
veil-color
w    7924
n      96
o      96
y       8
Name: count, dtype: int64

Column: ring-number
ring-number
o    7488
t     600
n      36
Name: count, dtype: int64

Column: ring-type
ring-type
p    3968
e    2776
l    1296
f      48
n      36
Name: count, dtype: int64

Column: spore-print-color
spore-print-color
w    2388
n    1968
k    1872
h    1632
r      72
u      48
o      48
y      48
b      48
Name: count, dtype: int64

Column: population
population
v    4040
y    1712
s    1248
n     400
a     384
c     340
Name: count, dtype: int64

Column: habitat
habitat
d    3148
g    2148
p    1144
l     832
u     368
m     292
w     192
Name: count, dtype: int64

# 2. Missimg Value

In [98]:
dataset.isnull().sum()

class                       0
cap-shape                   0
cap-surface                 0
cap-color                   0
bruises                     0
odor                        0
gill-attachment             0
gill-spacing                0
gill-size                   0
gill-color                  0
stalk-shape                 0
stalk-root                  0
stalk-surface-above-ring    0
stalk-surface-below-ring    0
stalk-color-above-ring      0
stalk-color-below-ring      0
veil-type                   0
veil-color                  0
ring-number                 0
ring-type                   0
spore-print-color           0
population                  0
habitat                     0
dtype: int64

In [99]:
# بررسی مقدار ?
(dataset == "?").sum()

class                          0
cap-shape                      0
cap-surface                    0
cap-color                      0
bruises                        0
odor                           0
gill-attachment                0
gill-spacing                   0
gill-size                      0
gill-color                     0
stalk-shape                    0
stalk-root                  2480
stalk-surface-above-ring       0
stalk-surface-below-ring       0
stalk-color-above-ring         0
stalk-color-below-ring         0
veil-type                      0
veil-color                     0
ring-number                    0
ring-type                      0
spore-print-color              0
population                     0
habitat                        0
dtype: int64

In [100]:
(dataset=='?').sum() / 8124

class                       0.000000
cap-shape                   0.000000
cap-surface                 0.000000
cap-color                   0.000000
bruises                     0.000000
odor                        0.000000
gill-attachment             0.000000
gill-spacing                0.000000
gill-size                   0.000000
gill-color                  0.000000
stalk-shape                 0.000000
stalk-root                  0.305268
stalk-surface-above-ring    0.000000
stalk-surface-below-ring    0.000000
stalk-color-above-ring      0.000000
stalk-color-below-ring      0.000000
veil-type                   0.000000
veil-color                  0.000000
ring-number                 0.000000
ring-type                   0.000000
spore-print-color           0.000000
population                  0.000000
habitat                     0.000000
dtype: float64

# 4. Duplicates

In [101]:
print("Duplicate rows:", dataset.duplicated().sum())

Duplicate rows: 0

# 5. Inconsistent Data

In [106]:
print("\nUnique values per column:")
for col in dataset.columns:
    print(col, ":", dataset[col].nunique())

Unique values per column:
class : 2
cap-shape : 6
cap-surface : 4
cap-color : 10
bruises : 2
odor : 9
gill-attachment : 2
gill-spacing : 2
gill-size : 2
gill-color : 12
stalk-shape : 2
stalk-root : 5
stalk-surface-above-ring : 4
stalk-surface-below-ring : 4
stalk-color-above-ring : 9
stalk-color-below-ring : 9
veil-type : 1
veil-color : 4
ring-number : 3
ring-type : 5
spore-print-color : 9
population : 6
habitat : 7

In [107]:
for col in dataset.columns:
    print(f"{col} unique values:", dataset[col].unique())

class unique values: ['p' 'e']
cap-shape unique values: ['x' 'b' 's' 'f' 'k' 'c']
cap-surface unique values: ['s' 'y' 'f' 'g']
cap-color unique values: ['n' 'y' 'w' 'g' 'e' 'p' 'b' 'u' 'c' 'r']
bruises unique values: ['t' 'f']
odor unique values: ['p' 'a' 'l' 'n' 'f' 'c' 'y' 's' 'm']
gill-attachment unique values: ['f' 'a']
gill-spacing unique values: ['c' 'w']
gill-size unique values: ['n' 'b']
gill-color unique values: ['k' 'n' 'g' 'p' 'w' 'h' 'u' 'e' 'b' 'r' 'y' 'o']
stalk-shape unique values: ['e' 't']
stalk-root unique values: ['e' 'c' 'b' 'r' '?']
stalk-surface-above-ring unique values: ['s' 'f' 'k' 'y']
stalk-surface-below-ring unique values: ['s' 'f' 'y' 'k']
stalk-color-above-ring unique values: ['w' 'g' 'p' 'n' 'b' 'e' 'o' 'c' 'y']
stalk-color-below-ring unique values: ['w' 'p' 'g' 'b' 'n' 'e' 'y' 'o' 'c']
veil-type unique values: ['p']
veil-color unique values: ['w' 'n' 'o' 'y']
ring-number unique values: ['o' 't' 'n']
ring-type unique values: ['p' 'e' 'l' 'f' 'n']
spore-print-color unique values: ['k' 'n' 'u' 'h' 'w' 'r' 'o' 'y' 'b']
population unique values: ['s' 'n' 'a' 'v' 'y' 'c']
habitat unique values: ['u' 'g' 'm' 'd' 'p' 'w' 'l']